server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fullsecurity
    username: postgres
    password: odilhon1985
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
